Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.boot_timeout = 600

    config.vm.provider "libvirt" do |hv|
        hv.driver = "qemu"
        hv.cpus = "2"
        hv.memory = "2000"
    end

    k3s_token= "bonjour_je_suis_bob"

    config.vm.define "ocussy" do |ocussy|
        ocussy.vm.network :private_network, ip: "192.168.56.110"
        ocussy.vm.hostname = "ocussyS"

        ocussy.vm.provision "shell", inline: <<-SHELL
            echo "Installation of K3s..."
            curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --node-ip 192.168.56.110 --flannel-iface eth1" K3S_TOKEN=#{k3s_token} sh -
        SHELL

        # copy files
        ocussy.vm.provision "file", source: "./deployment.yaml", destination: "/tmp/deployment.yaml"
        ocussy.vm.provision "file", source: "./config.yaml", destination: "/tmp/config.yaml"
        ocussy.vm.provision "file", source: "./service.yaml", destination: "/tmp/service.yaml"
        ocussy.vm.provision "file", source: "./ingress.yaml", destination: "/tmp/ingress.yaml"

        ocussy.vm.provision "shell", inline: <<-SHELL
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            
            echo "Waiting K3s..."
            
            while ! kubectl get nodes > /dev/null 2>&1; do
                sleep 5
            done

            echo "K3s is ready !"

            echo "Application deployment..."
            kubectl apply -f /tmp/config.yaml
            kubectl apply -f /tmp/service.yaml
            kubectl apply -f /tmp/deployment.yaml
            kubectl apply -f /tmp/ingress.yaml


            echo "Restarting deployments to apply changes..."
            kubectl rollout restart deployment/app1 || true
            kubectl rollout restart deployment/app2 || true
            kubectl rollout restart deployment/app3 || true
            
        SHELL
    end
end